### ISSUE TITLE
Praise and question

### ISSUE THREAD

**Issue by Saraissima** [KennethEvans/VS-CSPBrushInfo#1]
Thank you so much for writing this helpful little app. Clip Studio materials DB is still a hot mess, and this helps me make some sense of it and sometimes recover lost items. But I was wondering, once it's figured out where all the orphans are, is there any way to delete them from the DB? After all these years they take up a lot of space.

Thanks again --

A grateful if very late to the starting gate user :-)

**Comment by KennethEvans** [comment]
Yes, I do delete the orphans. They are SQLite databases. They can be edited. I use DB Browser for SQLite. There are several others out there. They are relational, so you do have to develop some understanding of the structure CSP uses. I am not a database expert, so I take care and have backups.

In the end, it's probably OK to leave them. Compared to the overall size of the database, they don't take up much space.

**Comment by Saraissima** [comment]
Oh, I see. All right, well if they're not taking up much actual space and they're not liable to confuse the rest of the database, I probably am better off leaving them alone. They certainly do clutter up the view though! Thanks very much for the answer.
